AlumniConnect/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

from os import listdir
from .  import views


favicon_view = RedirectView.as_view(url='/static/faviconnn.ico', permanent=True)
urlpatterns = []

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('', views.index, name='home'),
    path('admin/', admin.site.urls),
    path('login/', views.LoginFormView.as_view(), name='login'),
    #path('account/reset_password/', views.ResetPasswordRequestView.as_view(), name="reset_password"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/',views.signup, name = "signup"),
    path('register/', views.register, name='register'),
    path('newregister/', views.new_register, name='new_register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    path('confirm/', TemplateView.as_view(template_name='AlumniConnect/confirm_email.html'), name = 'confirm'),
    path('success/', TemplateView.as_view(template_name='AlumniConnect/account_success.html'), name = 'success'),
    re_path('^', include('django.contrib.auth.urls')),
    path('password/', views.change_password, name='change_password'),
    re_path(r'^profileedit/(?P<id>[a-zA-Z0-9]+)/$', views.profileedit, name='profileedit'),
    path('profile/', include('applications.alumniprofile.urls')),
    path('members/', include('applications.members.urls')),
    path('events/', include('applications.events_news.urls')),
    path('news/', include('applications.news.urls')),
    path('newsletter/', include('applications.publications.urls')),
    path('geolocation/', include('applications.geolocation.urls')),
    path('alumnibody/', views.alumniBody),
    path('alumnicard/', views.alumniCard, name='alumnicard'),
    path('gallery/', include('applications.gallery.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('awards/', include('applications.awards.urls')),
    path('chapter/', include('applications.chapter.urls')),
    path('adminportal/', include('applications.adminportal.urls')),
    path('jobs/', include('applications.job_posting.urls')),
    re_path(r'faviconnn.ico', favicon_view),
    path('constitution/', views.constitution, name='constitution'),
    #path('', views.index, name='home'),
]

if settings.DEBUG:
    

    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    
# admin.site.site_header = "IIITDMJ Alumni Association"
admin.site.site_header = "PVPIT Alumni Association"
admin.site.site_title = "Alumni Association"
admin.site.index_title = "Alumni Association Admin"

applications/alumniprofile/urls.py
from django.urls import re_path, path

from . import views

app_name = 'profile'

urlpatterns = [
    re_path(r'^(?P<username>[a-zA-Z0-9]{5,9})/$', views.profile, name='profile'),
    path('add_experience', views.add_experience, name='add_experience'),
    path('add_education', views.add_education, name='add_education'),
]

applications/members/urls.py
from django.urls import include, path, re_path

from . import views

app_name = 'members'

extrapatterns = [

    re_path(r'^(?P<programme>[.a-zA-Z]+)/(?P<branch>[A-Z]+)/$', views.branch, name="branch"),
    path('', views.batch, name="batch"),
]
urlpatterns = [
    re_path(r'^(?P<year>[0-9]{4})/', include(extrapatterns)),
    # old link
    # path('sacbody/', views.sacbody, name="sacbody"),
    # new link
    path('alumnibody/', views.alumnibody, name="alumnibody"),
    path('search/', views.search, name='search'),
    path('autosearch/', views.autoSearch, name='autosearch'),
    path('mapsearch/', views.mapSearch, name='mapsearch'),
    path('', views.index, name='index'),
]

applications/members/models.py
from django.db import models

# Create your models here.

applications/members/views.py
import json     

from django.shortcuts import render, redirect
from django.db.models import Count
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from applications.alumniprofile.models import Profile
from django.contrib import messages


# Create your views here.

def index(request):
    counts = Profile.objects.filter(verify=True).values('batch').order_by('-batch').annotate(count=Count('batch'))
    total = 0

    for batch, count in counts.values_list('batch', 'count'):
        total += count

    data = counts.values_list('batch', 'count')

    context = {
               'data': data,
               'total': total,
               }

    return render(request, "members/index.html",context)


def batch(request, year):

    programmes = Profile.objects.values_list('programme', flat=True).distinct()
    data = {}
    for row in programmes:
        # todo: change mail_sent to verify
        result = Profile.objects.filter(batch=year, programme=row, verify=True).values('branch').annotate(count=Count('branch'))
        data[row] = {}
        for item in result:
            data[row][item['branch']] = item['count']

    return render(request, "members/year.html", {'data': data, 'year': year})

@login_required
def branch(request, programme, year, branch):
    # todo: change mail_sent to verify
    alumni = Profile.objects.filter(programme=programme, batch=year, branch=branch, verify=True)
    alumni = alumni.order_by('roll_no')
    return render(request, "members/branch.html", {'data': alumni, 'batch': year, 'branch': branch})

# def sacbody(request):
#     return redirect('members:alumnibody')

def alumnibody(request):
    return render(request, "members/alumnibody.html")


@login_required
def search(request):
    profiles = Profile.objects.all()
    profiles_filtered = False

    if len(request.POST) > 1:
        if request.POST['search'] != '':
            key = request.POST['search']
            profiles = profiles.filter(name__icontains=key) | profiles.filter(
            roll_no__icontains=key) | profiles.filter(reg_no__icontains=key)
            profiles_filtered = True

        if request.POST['batch'] != '':
            batch = request.POST['batch']
            profiles = profiles.filter(batch=batch)
            profiles_filtered = True
            
        if request.POST['city'] != '':
            city = request.POST['city']
            profiles = profiles.filter(city__icontains=city)
            profiles_filtered = True

        if request.POST['programme'] != '':
            programme = request.POST['programme']
            profiles = profiles.filter(programme__icontains=programme)
            profiles_filtered = True

        if request.POST['branch'] != '':
            branch = request.POST['branch']
            profiles = profiles.filter(branch__icontains=branch)
            profiles_filtered = True

        if request.POST['org'] != '':  
            org = request.POST['org']
            profiles1 = profiles.filter(current_organisation__icontains=org)
            profiles2 = profiles.filter(current_university__icontains=org)
            profiles = profiles1 | profiles2
            profiles_filtered = True

    profiles = profiles.order_by('roll_no')

    if not profiles_filtered:
        # return empty queryset in case no filters are selected
        profiles = Profile.objects.none()

    context = {
        'profiles': profiles,
        'keyy': 1,
        'zero': len(profiles),
        'request': request.POST
    }
    
    if len(profiles):
        messages.success(request, f'Total {str(len(profiles))} Alumni Found')
    else:
        messages.error(request, "No Result Found")

    return render(request, "members/index.html", context)

def autoSearch(request):
    if request.is_ajax():
        # print(request.POST['term'], request.GET['te'])
        key = request.GET['term']
        search_qs = Profile.objects.filter(name__icontains=key) | Profile.objects.filter(
            roll_no__icontains=key) | Profile.objects.filter(reg_no__icontains=key)
        data = []
        for r in search_qs:
            data.append(r.name)
    else:
        data = 'fail'
    return JsonResponse(data, safe=False)


@login_required
def mapSearch(request):
    location = request.GET.get('search', '')
    city = location.split(',', 1)[0]

    profiles = Profile.objects.all()
    if city:
        profiles = Profile.objects.filter(city__icontains=city)
        profiles = profiles.order_by('name')
    else:
        profiles = Profile.objects.filter(city=city)

    context = {
        'profiles': profiles,
        'location': location,
        'keyy': 1,
        'zero': len(profiles),
        'map': True
    }
    return render(request, "members/index.html", context)

templates/members/branch.html
{% extends 'globals/base.html' %}
{% load static %}
{% load thumbnail %}

{% block title %}
Members of PVPIT Alumni Association
{% endblock %}

{% block body %}
{% include 'globals/navbar.html' %}

<div class="p-0 m-0 masthead-bg w-100 parallax shadow-sm" style="min-height:250px !important; height:270px !important; background-position-y: 270px"></div>
<div style="height:150px; min-height:150px;"></div>

<section class="bg-transparent" style="padding:3rem 0 5rem;">
    <div class="members-container container text-left p-2 mx-auto bg-light shadow-lg rounded">

        <div class="row mx-auto">
            <div class="col text-center">
                <h2 class="font-open-sans"><span class="badge btn-block badge-primary">Batch of {{batch}}, {{branch}}
                    </span></h2>
            </div>
        </div>

        <div class="row p-4 mx-auto">
            {% for item in data %}
            <div class="col-md-6 col-lg-4 col-xl-3 p-2 members-shadow-on-hover">
                <div class="card">
                    <!-- hover-zoomin"  style="max-width: 24rem; max-height: 35em;"> -->
                    <span class="border border-primary">
                        <div class="card-body">
                            <a href="{% url 'profile:profile' item.roll_no %}" class="text-decoration-none">
                                <p class="text-center card-title">
                                    {% if item.profile_picture %}
                                    <img src="{% thumbnail item.profile_picture  216x216 crop %}" class=" img-fluid " alt="" 
                                        style="object-fit:cover; object-position:50% 0%; max-width:216px; 
                                         max-height:216px; width:100%; height:216px; margin-bottom: 1rem;" >
                                    {% else %}
                                    <img src="{% static 'AlumniConnect/img/user.png' %}" class="img-fluid"
                                        alt="" height="200px" width="200px">
                                    {% endif %}
                                </p>
                                <p class="card-title font-open-sans font-weight-bold">{{item.name}}</p>
                            </a>
                            <p class="font-italic card-text font-open-sans"><i class="fas fa-map-marker-alt"></i>{{item.city}}</p>

                            <h4 class="text-center card-text">
                                {% if item.facebook %}<a href="{{item.facebook}}" target="_blank"><i
                                        class="fab fa-facebook-square"></i></a>{% endif %}
                                {% if item.linkedin %}<a href="{{item.linkedin}}" target="_blank"><i
                                        class="fab fa-linkedin"></i></a>{% endif %}
                                {% if item.instagram %}<a href="https://www.instagram.com/{{item.instagram}}" target="_blank"><i
                                        class="fab fa-instagram"></i></a>{% endif %}
                                {% if item.website %}<a href="{{item.website}}" target="_blank"><i
                                        class="fas fa-link"></i></a>{% endif %}
                            </h4>
                            
                        </div>
                    </span>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% include 'globals/footer.html' %}
{% endblock %}

templates/members/index.html
{% extends 'globals/base.html' %}
{% load static %}

{% block title %}
YearBook
{% endblock %}

{% block javascript %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        {% if request.programme %}
        $('select[name="programme"]').val('{{ request.programme}}') 
        {% endif %} 
        {% if request.branch %}
        $('select[name="branch"]').val('{{ request.branch}}') 
        {% endif %}
    });

    $(document).ready(function () {
        $("#search").autocomplete({
            source: "/members/autosearch/",
            minLength: 3,
            open: function () {
                setTimeout(function () {
                    $('.ui-autocomplete').css('z-index', 99).css('max-height', '200px').css(
                        'overflow-y', 'auto').css('overflow-x', 'hidden')
                }, 0);
            }
        });
    });
</script>
{% endblock %}

{% block body %}
<!-- <body id="page-top" class="font-open-sans" style="background-color: #eaedf5"> -->
{% include 'globals/navbar.html' %}

<div class="p-0 m-0 masthead-bg w-100 parallax"
    style="min-height:300px !important; height:300px !important; background-position-y: 300px"></div>

<header class="masthead text-center text-white d-flex" style="height:0px; min-height:300px;">
    <div class="container my-auto" style="margin-bottom:50px !important;">
        <div class="row">
            <div class="col-lg-8 mx-auto align-middle">
                <h1 class="text-uppercase mt-4">
                    <strong>YEAR-BOOK</strong>
                </h1>
            </div>
        </div>
    </div>
</header>

<section id="services" class="bg-primary p-1"></section>

<section class="bg-light" style="padding:0 !important;">
    <div class="container text-left p-2 mx-auto bg-light" style="padding:0 !important;">
        <div class="row w-100 mx-auto bg-primary rounded-bottom">
            <div class="col text-white text-center p-0 pt-4 pb-4">

                {% if keyy %}
                <a href="{% url 'members:index' %}" class="btn btn-dark btn-outline-primary mb-4 text-white"
                    style="font-size: 0.85rem;">
                    <i class="fa fa-arrow-left mr-2" style="color:inherit !important" aria-hidden="true"></i>
                    Filter by Graduation Year
                </a>
                {% endif %}
                <br>

                <span class="mx-auto text-uppercase h3"><strong>Search</strong></span><br>

                {% if not keyy %}
                <span class="mx-auto h6">from</span>
                <span class="mx-auto h6">{{total}} registered alumni</span>
                {% endif %}

                <div class="search-container m-3 p-3" style="margin:6px;">
                    <form method="POST" action="{% url 'members:search' %}">
                        {% csrf_token %}
                        <div class='row justify-content-center m-3'>
                            <input type="text" id="search" class="form-control col-5 mx-2"
                                placeholder="Name, Roll No or Reg No" name="search" value={{request.search}}>
                            <button type="submit" class="btn btn-dark col-1 rounded mx-2"><i
                                class="fa fa-search mx-auto"></i></button>
                        </div>
                        <div class='row justify-content-center m-3' id='filters'>
                            <input type='text' class='form-control col-2 mx-1' placeholder='Batch' name='batch'
                                value={{request.batch}}>
                            <select name="programme" class="custom-select col-2 mx-1">
                                <option selected value="">Programme</option>
                                <option value="B.Tech">B.Tech</option>
                                <option value="B.Des">B.Des</option>
                                <option value="M.Tech">M.Tech</option>
                                <option value="M.Des">M.Des</option>
                                <option value="PhD">PhD</option>
                            </select>
                            <select name="branch" class="custom-select col-2 mx-1">
                                <option selected value="">Branch</option>
                                <option value="CSE">Computer Science and Engineering</option>
                                <option value="ECE">Electronics and Communication Engineering</option>
                                <option value="ME">Mechanical Engineering</option>
                                <option value="NS">Natural Sciences</option>
                                <option value="MT">Mechatronics</option>
                                <option value="DS">Design</option>
                            </select>
                            <input type="text" class="form-control col-2 mx-1" placeholder="City" name="city"
                                value={{request.city}}>
                            <input type="text" class="form-control col-2 mx-1" placeholder="Company/Institution" name="org"
                                value={{request.org}}>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="bg-light" style="padding:0 0 5rem;">
    <div class="container text-left p-2 mx-auto bg-light" style="padding-top:0 !important">

        {% comment %}
        <div class="row w-100 mx-auto">
            <div class="col">
                {% if not keyy %}
                <h2 class="font-open-sans"><span class="badge btn-block badge-primary"> Registered Alumni :
                        {{total}}</span></h2>
                {% else %}
                <h2 class="font-open-sans"><span class="badge btn-block badge-primary"></span></h2>
                {% endif %}
            </div>
            <div class="col">
                <form method="GET" action="{% url 'members:search' %}">
                    <div class="ui search">
                        <div class="ui action input">
                            <input type="text" name="q" placeholder="Search text ...">
                            <button type="submit" class="ui button"><i class="search icon"></i></button>
                        </div>
                        <div class="results"></div>
                    </div>
                </form>
            </div>
        </div>
        {% endcomment %}

        <div class="row mx-auto">
            <div class="col text-center">
                {% if not keyy %}
                <h2 class="font-open-sans"><span class="badge btn-block badge-primary text-wrap mt-2"> Alumni by
                    Graduation Year</span></h2>
                {% elif map %}
                <h2 class="font-open-sans"><span class="badge btn-block badge-primary text-wrap mt-2"> Alumni in '{{location}}'</span></h2>
                    {% if not zero %}
                    <div class="alert alert-danger" role="alert">
                        No Results Found!
                    </div>
                    {% endif %}
                {% endif %}

                <!-- {% if zero %}
                <h2 class="font-open-sans"><span class="badge btn-block badge-primary text-wrap mt-2"> Total {{zero}} Alumni Found</span></h2>
                 {% endif %} -->

                {% for message in messages %}
                <br>
                <div class="alert alert-{% if message.tags == 'success' %}primary {% else %}danger{% endif %} alert-dismissible fade show mb-4" role="alert">
                    <strong>Message : </strong> {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            </div>
        </div>

        {% if not keyy %}
        <div class="row p-4 mx-auto">
            {% for batch,count in data %}
            <div class="col-lg-3 col-md-4 col-sm-6 p-2 members-shadow-on-hover">
                <div class="card w-100 text-center mx-auto" style="max-width: 15rem; max-height: 40rem;">
                    <div class="card-body">
                        <h5 class="card-title font-weight-bold"><a href="{% url 'members:batch' batch %}"
                                class="text-decoration-none stretched-link">Batch of {{ batch }}</a></h5>

                        <p class="m-2 font-italic  font-open-sans">{{ count }} Member{{ count|pluralize }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% else %}

        <div class="row mx-auto">
            {% for item in profiles %}
            <div class="col-md-6 col-lg-4 col-xl-3 p-2 members-shadow-on-hover">
                <div class="card">
                    <!-- hover-zoomin"  style="max-width: 24rem; max-height: 35em;"> -->
                    <span class="border border-primary">
                        <div class="card-body">
                            <a href="{% url 'profile:profile' item.roll_no %}" class="text-decoration-none">
                                <p class="text-center card-title">
                                    {% if item.profile_picture %}
                                    <img src="{{ item.profile_picture.url }}" class="img-fluid" alt="" style="object-fit:cover; object-position:50% 0%; max-width:216px; 
                                            max-height:216px; width:100%; height:216px; margin-bottom: 1rem;">
                                    {% else %}
                                    <img src="{% static 'AlumniConnect/img/user.png' %}" class="img-fluid" alt=""
                                        height="200px" width="200px">
                                    {% endif %}
                                </p>
                                <p class="card-title font-open-sans font-weight-bold">{{item.name}}</p>
                            </a>
                            <p class="font-italic card-text font-open-sans"><i class="fas fa-map-marker-alt"></i>
                                {{item.city}}</p>

                            <h4 class="text-center card-text">

                                {% if item.facebook %}<a href="{{item.facebook}}" target="_blank"><i
                                        class="fab fa-facebook-square"></i></a>{% endif %}
                                {% if item.linkedin %}<a href="{{item.linkedin}}" target="_blank"><i
                                        class="fab fa-linkedin"></i></a>{% endif %}
                                {% if item.website %}<a href="{{item.website}}" target="_blank"><i
                                        class="fas fa-link"></i></a>{% endif %}

                            </h4>
                        </div>
                    </span>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}

    </div>
</section>

{% include 'globals/footer.html' %}
{% endblock %}

templates/members/search.html
{% extends 'globals/base.html' %}
{% load static %}

{% block title %}
YearBook
{% endblock %}

{% block body %}
{% include 'globals/navbar.html' %}

<div class=" p-0 m-0 masthead-bg w-100 parallax shadow-sm"
    style="min-height:250px !important;height:270px !important;background-position-y: -400px">

</div>

<div style="height:170px;min-height: 150px;">
</div>

<section class="bg-transparent" style="padding-top:3rem">
    <div class="container text-left p-2 mx-auto bg-light">

        <div class="row w-100">
            <div class="col text-center">
                <h2 class="font-open-sans"><span class="badge btn-block badge-primary"> Search Result
                    </span></h2>
            </div>
            <div class="search-container" style="margin:6px;">
                <form method="GET" action="{% url 'members:search' %}">
                    <input type="text" placeholder="Search.." name="search" value={{val}}>
                    <button type="submit"><i class="fa fa-search"></i></button>
                </form>
            </div>
        </div>

        <div class="row p-4">
            {% for item in data %}
            <div class="col-lg-3 p-2">
                    <span class="border border-primary">
                        <div class="card-body">
                            <p class="text-center card-title">
                                <a href="{% url 'profile:profile' item.roll_no %}">
                                    {% if item.profile_picture %}
                                    
                                    <img  src="{% thumbnail item.profile_picture  200x200 crop %}" class=" img-fluid " alt="">
                                    {% else %}
                                    <img src="{% static 'AlumniConnect/img/user.png' %}" class="card-img-top img-fluid"
                                        alt="" height="200px" width="200px">
                                    {% endif %}

                            </p>
                            <p class="card-title font-open-sans font-weight-bold">{{item.name}}</a></p>
                            <p class="font-italic card-text font-open-sans"><i class="fas fa-map-marker-alt"></i>
                                {{item.city}}</p>

                            <h4 class="text-center card-text">

                                {% if item.facebook %}<a href="{{item.facebook}}" target="_blank"><i
                                        class="fab fa-facebook-square"></i></a>{% endif %}
                                {% if item.linkedin %}<a href="{{item.linkedin}}" target="_blank"><i
                                        class="fab fa-linkedin"></i></a>{% endif %}
                                {% if item.instagram %}<a href="https://www.instagram.com/{{item.instagram}}" target="_blank"><i
                                        class="fab fa-instagram"></i></a>{% endif %}
                                {% if item.website %}<a href="{{item.website}}" target="_blank"><i
                                        class="fas fa-link"></i></a>{% endif %}

                            </h4>


                        </div>


                </div>
                </span>

            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% include 'globals/footer.html' %}
{% endblock %}

templates/members/year.html
{% extends 'globals/base.html' %}
{% load static %}

{% block title %} 
     Members of PVPIT Alumni Association
{% endblock %}

{% block body %}
  <!-- <body id="page-top" class="font-open-sans" style="background-color: #eaedf5"> -->
    {% include 'globals/navbar.html' %}

    <div class="p-0 m-0 masthead-bg w-100 parallax shadow-sm" style="min-height:250px !important; height:270px !important; background-position-y: 270px;"></div>
    <div style="height:150px; min-height:150px;"></div>
    
    <section class="bg-transparent" style="padding:3rem 0 5rem;">
        <div class="members-container container text-left p-2 mx-auto bg-light shadow-lg rounded">
                <div class="row mx-auto">
                        <div class="col text-center">
                            <h2 class="font-open-sans"><span class="badge btn-block badge-primary">Graduation Year : {{year}} </span></h2>
                        </div>
                    </div>
            {% for key1, value1 in data.items %}
            {% if value1 %}
            <div class="row mx-auto">
                <div class="col text-center">
                    <h2 class="font-open-sans"><span class="badge badge-primary">{{ key1 }}</span></h2>
                </div>
            </div>

            <div class="row p-4 mx-auto">
                {% for key2, value2 in value1.items %}
                <div class="col-lg-3 col-md-4 col-sm-6 p-2 members-shadow-on-hover">
                    <div class="card w-100 text-center mx-auto" style="max-width: 15rem; max-height: 40rem;">
                        <div class="card-body">
                            <h5 class="card-title font-weight-bold">
                                <a href="{% url 'members:batch' year=year %}{{key1}}/{{key2}}/" class="text-decoration-none stretched-link"> {{ key2}} <br>{{ value2 }} Member{{ value2|pluralize }} </a>
                            </h5>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

            {% endif %}
            {% endfor %}

        </div>
    </section>
    {% include 'globals/footer.html' %} 
{% endblock %}