AlumniConnect/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

from os import listdir
from .  import views


favicon_view = RedirectView.as_view(url='/static/faviconnn.ico', permanent=True)
urlpatterns = []

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('', views.index, name='home'),
    path('admin/', admin.site.urls),
    path('login/', views.LoginFormView.as_view(), name='login'),
    #path('account/reset_password/', views.ResetPasswordRequestView.as_view(), name="reset_password"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/',views.signup, name = "signup"),
    path('register/', views.register, name='register'),
    path('newregister/', views.new_register, name='new_register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    path('confirm/', TemplateView.as_view(template_name='AlumniConnect/confirm_email.html'), name = 'confirm'),
    path('success/', TemplateView.as_view(template_name='AlumniConnect/account_success.html'), name = 'success'),
    re_path('^', include('django.contrib.auth.urls')),
    path('password/', views.change_password, name='change_password'),
    re_path(r'^profileedit/(?P<id>[a-zA-Z0-9]+)/$', views.profileedit, name='profileedit'),
    path('profile/', include('applications.alumniprofile.urls')),
    path('members/', include('applications.members.urls')),
    path('events/', include('applications.events_news.urls')),
    path('news/', include('applications.news.urls')),
    path('newsletter/', include('applications.publications.urls')),
    path('geolocation/', include('applications.geolocation.urls')),
    path('alumnibody/', views.alumniBody),
    path('alumnicard/', views.alumniCard, name='alumnicard'),
    path('gallery/', include('applications.gallery.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('awards/', include('applications.awards.urls')),
    path('chapter/', include('applications.chapter.urls')),
    path('adminportal/', include('applications.adminportal.urls')),
    path('jobs/', include('applications.job_posting.urls')),
    re_path(r'faviconnn.ico', favicon_view),
    path('constitution/', views.constitution, name='constitution'),
    #path('', views.index, name='home'),
]

if settings.DEBUG:
    

    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    
# admin.site.site_header = "IIITDMJ Alumni Association"
admin.site.site_header = "PVPIT Alumni Association"
admin.site.site_title = "Alumni Association"
admin.site.index_title = "Alumni Association Admin"

applications/chapter/urls.py
from django.urls import path, re_path

from . import views

app_name = 'chapter'

urlpatterns = [
    re_path(r'^(?P<id>[0-9])/$', views.chapter_redirect, name='chapter_redirect'),
    path('images/', views.chapter_images, name='chapter_images'),
    re_path(r'^r/(?P<id>[0-9])/$', views.chapter, name='chapter'),
    path('', views.index, name='index')
]

applications/events_news/urls.py
from django.urls import path, re_path

from . import views

app_name = 'events_news'

urlpatterns = [
    re_path(r'^event/(?P<id>[0-9]+)/$', views.event, name='event'),
    path('', views.events, name='events'),
]

applications/chapter/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from applications.alumniprofile.models import Profile
from applications.events_news.models import Event
from applications.gallery.models import Album


def upload_photo(instance, filename):
    name, extension = os.path.splitext(filename)
    return 'Chapter_Walls/' + str(instance.name) + ".jpg"


class Constants:
    POST = (
        ('President', 'President'),
        ('Hon. Secretary', 'Hon. Secretary'),
        ('Treasurer', 'Treasurer'),
        ('Other', 'Other')
    )


class Chapters(models.Model):
    name = models.CharField(max_length=100)
    description = RichTextUploadingField(blank=True, null=True)
    wall_picture = models.ImageField(null=True, blank=True, upload_to=upload_photo)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class ChapterTeam(models.Model):
    chapter = models.ForeignKey(Chapters, on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    post = models.CharField(choices=Constants.POST, max_length=50)
    other_post = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return 'Chapter: ' + str(self.chapter) + ' User: ' + str(self.user) + ' Post: ' + str(self.post)


class ChapterEvent(models.Model):
    chapter = models.ForeignKey(Chapters, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('chapter', 'event'),)

    def __str__(self):
        return 'Chapter: ' + str(self.chapter) + ' Event: ' + str(self.event)


class ChapterAlbum(models.Model):
    chapter = models.ForeignKey(Chapters, on_delete=models.CASCADE)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('chapter', 'album'),)

    def __str__(self):
        return 'Chapter: ' + str(self.chapter) + ' Event: ' + str(self.album)

applications/chapter/forms.py
from django import forms
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from tempus_dominus.widgets import DateTimePicker
from applications.gallery.models import Album
from applications.events_news.models import Event
from .models import Chapters


class DescriptionForm(forms.ModelForm):
    description = forms.CharField(
        widget=CKEditorUploadingWidget(
            attrs={'id': 'chapter_description'}
        ),
        required=False
    )

    class Meta:
        model = Chapters
        fields = ['description', 'wall_picture']


class EventForm(forms.ModelForm):
    description = forms.CharField(
        widget=CKEditorUploadingWidget(
            attrs={'id': 'event_description'}
        )
    )
    title = forms.CharField(
        widget=CKEditorUploadingWidget(
            attrs={'id': 'event_title'}
        )
    )
    start_date = forms.DateTimeField(
        widget=DateTimePicker(
            options={
                'useCurrent': True,
                'format': 'YYYY-MM-DD HH:mm:ss',
                'icons': {
                    'time': 'fa fa-clock',
                    'today': 'fa fa-calendar-check',
                    'clear': 'fa fa-trash'
                }
            },
            attrs={
                'append': 'fa fa-calendar'
            }
        ),
    )
    end_date = forms.DateTimeField(
        widget=DateTimePicker(
            options={
                'useCurrent': True,
                'format': 'YYYY-MM-DD HH:mm:ss',
                'icons': {
                    'time': 'fa fa-clock',
                    'today': 'fa fa-calendar-check',
                    'clear': 'fa fa-trash'
                }
            },
            attrs={
                'append': 'fa fa-calendar'
            }
        ),
    )

    class Meta:
        model = Event
        exclude = []


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        exclude = ['slug', 'is_visible', 'created', ]

    zip = forms.FileField(required=False)

applications/chapter/views.py
import zipfile, uuid
from datetime import datetime
from zipfile import ZipFile
from PIL import Image

from django.conf import settings
from django.core.files.base import ContentFile
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.utils.html import strip_tags
from applications.alumniprofile.models import Profile
from applications.gallery.models import AlbumImage, Album
from .models import *
from .forms import *


# Create your views here.
def index(request):
    chapters = Chapters.objects.all()
    context = {
        'chapters': chapters,
    }
    return render(request, 'chapter/index.html', context)


def chapter_data(request, id):
    chapter = Chapters.objects.get(pk=id)
    post = ChapterTeam.objects.filter(chapter=chapter)
    event = ChapterEvent.objects.filter(chapter=chapter)
    album = ChapterAlbum.objects.filter(chapter=chapter)
    team = []
    for i in post:
        prof = Profile.objects.get(user=i.user)
        t = {'name': str(prof.name), 'post': str(i.post), 'email': str(prof.email),
             'pic': str(prof.profile_picture.url)}
        team.append(t)
    context = {
        'chapter': chapter,
        'team': team,
        'event': event,
        'album': album
    }
    if request.user.is_authenticated and ChapterTeam.objects.filter(chapter=chapter, user=request.user).exists():
        forms = {
            'eventf': EventForm(),
            'chapterf': DescriptionForm(instance=chapter),
            'albumf': AlbumForm()
        }
        context.update(forms)
    return context


def chapter(request, id):
    res = 'GET Request'
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
        if 'chapter' in request.POST:
            res = chapter_edit(request, id)
        elif 'event' in request.POST:
            res = event_add(request, id)
        elif 'album' in request.POST:
            res = album_add(request, id)
        else:
            res = 'Unknown Form'
    print(res)
    # return render(request, 'chapter/chapter.html', context)
    return redirect('chapter:chapter_redirect', id=id)


def chapter_redirect(request, id):
    context = chapter_data(request, id)
    return render(request, 'chapter/chapter.html', context)


def chapter_images(request):
    if request.is_ajax():
        id = request.GET['album']
        album = Album.objects.get(pk=id)
        images = AlbumImage.objects.filter(album=album)
        data = []
        for i in images:
            data.append({'src': i.image.url, 'h': i.height, 'w': i.width})
    else:
        data = 'fail'
    return JsonResponse(data, safe=False)


def chapter_edit(request, id):
    if request.method == 'POST':
        chapter = Chapters.objects.get(pk=id)
        form = DescriptionForm(request.POST, request.FILES, instance=chapter)
        if form.is_valid():
            chapter = form.save()
            chapter.save()
            return 'Success'
        return 'Form is not Valid'
    return 'Request method is not POST'


def event_add(request, id):
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES)
        print(request.POST['start_date'], request.POST['end_date'])
        if form.is_valid():
            event = form.save()
            event.save()
            chapter = Chapters.objects.get(pk=id)
            chapter_event = ChapterEvent(chapter=chapter, event=event)
            chapter_event.save()
            return 'Success'
        else:
            print(form.errors)
            return 'Form is not Valid'
    return 'Request method is not POST'


def album_add(request, id):
    if request.method == 'POST':
        form = AlbumForm(request.POST, request.FILES)
        if form.is_valid():
            album = form.save(commit=False)
            album.created = datetime.now()
            album.is_visible = True
            album.slug = strip_tags(album.title)
            album.save()

            if form.cleaned_data['zip'] is not None:
                zip = zipfile.ZipFile(form.cleaned_data['zip'])
                for filename in sorted(zip.namelist()):

                    file_name = os.path.basename(filename)
                    if not file_name or file_name.startswith('.'):
                        continue

                    data = zip.read(filename)
                    contentfile = ContentFile(data)

                    img = AlbumImage()
                    img.album = album
                    img.alt = filename
                    filename = '{0}{1}.jpg'.format(album.slug, str(uuid.uuid4())[-13:])
                    img.image.save(filename, contentfile)

                    filepath = '{0}/Albums/{1}'.format(settings.MEDIA_ROOT, filename)
                    with Image.open(filepath) as i:
                        img.width, img.height = i.size

                    img.thumb.save('thumb-{0}'.format(filename), contentfile)
                    img.save()
                zip.close()

            chapter = Chapters.objects.get(pk=id)
            chapter_album = ChapterAlbum(chapter=chapter, album=album)
            chapter_album.save()
            return 'Success'
        return 'Form is not Valid'
    return 'Request method is not POST'

templates/chapter/chapter.html
{% extends 'globals/base.html' %}
{% load static %}

{% block title %}
{{chapter.name}} - PVPIT Bavdhan
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'chapter/chapter.css' %}" />
<link rel="stylesheet" href="{% static 'external/photoswipe/photoswipe.css' %}" />
<link rel="stylesheet" href="{% static 'external/photoswipe/default-skin/default-skin.css' %}" />
{% endblock %}

{% block body %}
{% include 'globals/navbar.html' %}

<div class="mt-5 overlay-image">
  {% if chapter.wall_picture %}
  <img class="image" src="{{ chapter.wall_picture.url }}" alt="Alt text" />
  {% else %}
  <img class="image" src="{% static 'AlumniConnect/img/coll3.jpeg' %}" alt="Alt text" />
  {% endif %}

  <div class="text text-center">
    <h1 class="text-uppercase" style="font-size: 4rem; font-weight: bold;">{{chapter.name}}</h1>
  </div>
</div>

<section id="services" class="bg-primary p-1">
</section>

<div class="container">
  <div class="row my-5">
    {% for item in team %}
    <div class="col-xl-4 col-md-6 mb-4 mx-auto">
      <div class="card border-1">
        {% if item.pic %}
        <img src="{{ item.pic }}" class="card-img-top" alt="{{item.name}}"
          style="object-fit:cover; max-width:350px; max-height:245px; height:245px;">
        {% else %}
        <img src="{% static 'AlumniConnect/img/coll3.jpeg' %}" class="card-img-top" alt="..."
          style="object-fit:cover; max-width:350px; max-height:245px; height:245px;">
        {% endif %}
        <div class="card-body text-center">
          <h5 class="card-title mb-0">{{item.name}}</h5>
          <div class="card-text text-black-50">{{item.post}}<br>{{item.email}}</div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% if chapter.description or chapterf %}
<div class="container" <div class="card m-2 shadow-sm">
  <div class="border-bottom p-3">
    <h4>
      Description
      {% if chapterf %}
      <button type="button" class="btn btn-link float-right" title="Edit Description" data-toggle="modal"
        data-target="#chapterModal" data-backdrop="static">
        <i class="fas fa-edit"></i>
      </button>
      {% endif %}
    </h4>
  </div>
  <div class="card-body p-4">
    <h6>{{chapter.description|safe}}</h6>
  </div>
</div>
</div>
{% endif %}

{% if event or eventf %}
<div class="container">
  <div class="border-bottom p-3 mb-2">
    <h4>
      Events
      {% if eventf %}
      <button type="button" class="btn btn-link float-right" title="Add Events" data-toggle="modal"
        data-target="#eventModal" data-backdrop="static">
        <i class="fas fa-plus"></i>
      </button>
      {% endif %}
    </h4>
  </div>
  <div class="row p-3">
    {% for item in event %}
    <div class="card mb-3 mx-1" style="max-width: 540px; width: 50%; cursor: pointer"
      onclick="location.href='{% url 'events_news:event' id=item.event.event_id %}'">
      <div class="row no-gutters">
        <div class="col-md-4 my-auto pl-2">
          {% if item.event.picture %}
          <img src="{{item.event.picture.url}}" class="card-img" alt="...">
          {% else %}
          <img src="{% static 'AlumniConnect/img/coll3.jpeg' %}" class="card-img" alt="...">
          {% endif %}
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">{{item.event.title|safe}}</h5>
            <h6 class="card-text m-1 mt-3">
              <small class="text-muted">
                <i class="fas fa-table mr-2"></i>
                {{ item.event.start_date|date:"d F, o" }}<br>
                <i class="fas fa-map-marker-alt mr-2"></i>&nbsp;
                {{ item.event.location}}<br>
                <i class="fas fa-user mr-2"></i>
                {{ item.event.by }}
              </small>
            </h6>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endif %}

{% if album or albumf %}
<div class="container">
  <div class="border-bottom p-3 mb-2">
    <h4>
      Album
      {% if albumf %}
      <button type="button" class="btn btn-link float-right" title="Add Album" data-toggle="modal"
        data-target="#albumModal" data-backdrop="static">
        <i class="fas fa-plus"></i>
      </button>
      {% endif %}
    </h4>
  </div>
  <div class="row p-3">
    {% for item in album %}
    <div class="card mb-3 mx-3" style="max-width: 540px; width: 22%; cursor: pointer"
      onclick="location.href='javascript:chapteralbum({{ item.album.id }});'">
      {% if item.album.thumb.url %}
      <img class="card-img-top" src="{{ item.album.thumb.url }}" alt="{{ item.album.title|striptags }}">
      {% else %}
      <img class="card-img-top" src="{% static 'AlumniConnect/img/album.png' %}" alt="Album">
      {% endif %}
      <div class="card-body">
        <h5 class="card-title border-bottom">{{ item.album.title|safe }}</h5>
        <small class="text-muted">
          {{ item.album.description|safe|truncatechars:150 }}<br>
        </small>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% include 'globals/init_pwsp.html' %}
{% endif %}
{% if chapterf and eventf and albumf %}
{% include 'chapter/modal.html' %}
{% endif %}
{% include 'globals/footer.html' %}
{% endblock %}

{% block javascript %}
<script>
  var chapteralbum = function (album) {
    $.ajax({
      url: '/chapter/images?album=' + album,
      contentType: "application/json",
      dataType: 'json',
      success: function (result) {
        var pswpElement = document.querySelectorAll('.pswp')[0];
        var options = {
          index: 0,
          bgOpacity: 0.8,
          captionEl: false,
          tapToClose: true,
          fullscreenEl: false,
        };
        var gallery = new PhotoSwipe(pswpElement, PhotoSwipeUI_Default, result, options);
        gallery.init();
      }
    });
  }
</script>
<script src="{% static 'external/photoswipe/photoswipe.min.js' %}"></script>
<script src="{% static 'external/photoswipe/photoswipe-ui-default.min.js' %}"></script>
{% endblock %}

templates/chapter/index.html
{% extends 'globals/base.html' %}
{% load static %}

{% block title %}
Chapters
{% endblock %}

{% block css %}
<link rel="stylesheet" href='{% static "chapter/chapter.css" %}' />
{% endblock %}

{% block body %}
{% include 'globals/navbar.html' %}
<div class="p-0 m-0 masthead-bg w-100 parallax shadow-sm"
    style="min-height:300px !important; height:300px !important; background-position-y: 300px;"></div>
<!-- <div style="height:150px; min-height: 150px;"></div> -->

<header class="masthead text-center text-white d-flex" style="height:0px; min-height:300px;">
    <div class="container my-auto" style="margin-bottom:50px !important;">
        <div class="row">
            <div class="col-lg-8 mx-auto align-middle">
                <h1 class="text-uppercase mt-4">
                    <strong>CHAPTERS</strong>
                </h1>
            </div>
        </div>
    </div>
</header>

<section id="services" class="bg-primary p-1">
</section>

<div class="container">
    <div class="row my-5">
        {% for item in chapters %}
        <div class="col-xl-4 col-md-6 mb-4 mx-auto" style="cursor: pointer"
            onclick="location.href='{% url 'chapter:chapter' item.id %}'">
            <div class="card border-0 shadow shadow-on-hover">
                {% if item.wall_picture %}
                <img src="{{ item.wall_picture.url }}" class="card-img-top" alt="{{item.name}}"
                    style="object-fit:cover; max-width:350px; max-height:245px; height:245px;">
                {% else %}
                <img src="{% static 'AlumniConnect/img/coll3.jpeg' %}" class="card-img-top" alt="..."
                    style="object-fit:cover; max-width:350px; max-height:245px; height:245px;">
                {% endif %}
                <div class="card-body text-center">
                    <h5 class="card-title mb-0">{{item.name}}</h5>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<!-- <div class="container">
    <h6>
        <small class="form-text text-muted">Want to start a new <b>Alumni Chapter</b>. Contact us at <a
                href="mailto:alumni@iiitdmj.ac.in">alumni@iiitdmj.ac.in</a> </small>
    </h6>
</div> -->
{% include 'globals/footer.html' %}
{% endblock %}

templates/chapter/modal.html
{% load crispy_forms_tags %}

<!-- Chapter Modal -->
<div class="modal fade" id="chapterModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Chapter Description</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            <form action="{% url 'chapter:chapter' chapter.id %}" method="POST" role="form"
                enctype="multipart/form-data" class="post-form">
                {% csrf_token %}
                <div class="modal-body">
                    {{ chapterf.media }}
                    {{ chapterf|crispy }}
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success" name="chapter">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>


<!-- Event Modal -->
<div class="modal fade" id="eventModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Event</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            <form action="{% url 'chapter:chapter' chapter.id %}" method="POST" role="form"
                enctype="multipart/form-data" class="post-form">
                {% csrf_token %}
                <div class="modal-body">
                    {{ eventf.media }}
                    {{ eventf|crispy }}
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success" name="event">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>


<!-- Album Modal -->
<div class="modal fade" id="albumModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Album</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            <form action="{% url 'chapter:chapter' chapter.id %}" method="POST" role="form"
                enctype="multipart/form-data" class="post-form">
                {% csrf_token %}
                <div class="modal-body">
                    {{ albumf.media }}
                    {{ albumf|crispy }}

                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success" name="album">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>