AlumniConnect/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

from os import listdir
from .  import views


favicon_view = RedirectView.as_view(url='/static/faviconnn.ico', permanent=True)
urlpatterns = []

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('', views.index, name='home'),
    path('admin/', admin.site.urls),
    path('login/', views.LoginFormView.as_view(), name='login'),
    #path('account/reset_password/', views.ResetPasswordRequestView.as_view(), name="reset_password"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/',views.signup, name = "signup"),
    path('register/', views.register, name='register'),
    path('newregister/', views.new_register, name='new_register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    path('confirm/', TemplateView.as_view(template_name='AlumniConnect/confirm_email.html'), name = 'confirm'),
    path('success/', TemplateView.as_view(template_name='AlumniConnect/account_success.html'), name = 'success'),
    re_path('^', include('django.contrib.auth.urls')),
    path('password/', views.change_password, name='change_password'),
    re_path(r'^profileedit/(?P<id>[a-zA-Z0-9]+)/$', views.profileedit, name='profileedit'),
    path('profile/', include('applications.alumniprofile.urls')),
    path('members/', include('applications.members.urls')),
    path('events/', include('applications.events_news.urls')),
    path('news/', include('applications.news.urls')),
    path('newsletter/', include('applications.publications.urls')),
    path('geolocation/', include('applications.geolocation.urls')),
    path('alumnibody/', views.alumniBody),
    path('alumnicard/', views.alumniCard, name='alumnicard'),
    path('gallery/', include('applications.gallery.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('awards/', include('applications.awards.urls')),
    path('chapter/', include('applications.chapter.urls')),
    path('adminportal/', include('applications.adminportal.urls')),
    path('jobs/', include('applications.job_posting.urls')),
    re_path(r'faviconnn.ico', favicon_view),
    path('constitution/', views.constitution, name='constitution'),
    #path('', views.index, name='home'),
]

if settings.DEBUG:
    

    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    
# admin.site.site_header = "IIITDMJ Alumni Association"
admin.site.site_header = "PVPIT Alumni Association"
admin.site.site_title = "Alumni Association"
admin.site.index_title = "Alumni Association Admin"

applications/adminportal/urls.py
from django.urls import path

from . import views

app_name = 'adminportal'

urlpatterns = [
    path('', views.index, name='index'),
    path('events', views.events, name='events'),
    path('mailservice', views.mailservice_index, name='mailservice'),
    path('registrations', views.registrations_index, name='registrations'),
]

applications/adminportal/models.py
from django.db import models

# Create your models here.
class EmailTemplate(models.Model):
    template_id = models.CharField(max_length=50, unique=True)
    name = models.CharField(max_length=100)
    subject = models.CharField(max_length=500)
    body = models.TextField()

    def __str__(self):
        return self.name


class EmailHistory(models.Model):
    email_template = models.CharField(max_length=100)
    programme = models.CharField(max_length=250)
    batch = models.CharField(max_length=250)
    branch = models.CharField(max_length=250)
    timestamp = models.DateTimeField(auto_now_add=True)
    total_recipients = models.IntegerField()
    total_delivered = models.IntegerField()

    def __str__(self):
        return self.email_template

applications/adminportal/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.sites.shortcuts import get_current_site
from django.core import mail
from django.core.mail import EmailMultiAlternatives
from django.db.models import Sum
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template import Context, Template
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.html import strip_tags

from datetime import date, datetime

from applications.alumniprofile.models import Profile
from applications.events_news.models import Event
from .models import EmailTemplate, EmailHistory

import pytz

ALLOWED_RECIPIENTS_PER_DAY = 500


def is_superuser(user):
    return user.is_superuser


 
def get_rendered_emails(from_email, email_template, recipients):
    subject = email_template.subject

    body = email_template.body
    body_template = Template(body)

    messages = []
    bcc=settings.BCC_EMAILS

    for profile in recipients:  
        bcc.append(profile.email)

    context = Context({
            "profile": profile,
        })

    html_message = body_template.render(context)
    plain_message = strip_tags(html_message)
    
    email = EmailMultiAlternatives(
            subject,
            plain_message,
            from_email,
            ['alumni@iiitdmj.ac.in'],
            bcc ,
            # settings.BCC_EMAILS,
        )
    email.attach_alternative(html_message, "text/html")
    messages.append(email)

    return messages
    
@login_required
@user_passes_test(
    is_superuser, redirect_field_name=None,
    login_url=reverse_lazy('home')
)
def index(request):
    return render(request, 'adminportal/index.html')


#Function to convert datetime from naive to offset
def convert_datetime_to_offset(naive_time):
    timezone = pytz.timezone("UTC")
    offset_time = timezone.localize(datetime.strptime(naive_time, '%Y-%m-%dT%H:%M'))
    return offset_time


#Function to convert datetime from offset to naive
def convert_datetime_to_naive(offset_time):
    offset_time = str(offset_time)
    naive_time = offset_time[:10] + "T" +  offset_time[11:-6]
    return naive_time


@login_required
@user_passes_test(
    is_superuser, redirect_field_name=None,
    login_url=reverse_lazy('home')
)
def events(request):
    if request.method == 'POST':
        try:
            title = request.POST['title']
            description = request.POST['description']
            start_date_time = request.POST['start_date_time']
            end_date_time = request.POST['end_date_time']
            address = request.POST['address']
            location = request.POST['location']
            by = request.POST['organiser']
            picture = request.FILES.get('cover_image')
            
            start_date_time = convert_datetime_to_offset(start_date_time)
            end_date_time = convert_datetime_to_offset(end_date_time)

            if(end_date_time <= start_date_time):
                messages.error(request, f"Start date & time should be less than end date & time.")
                return redirect('adminportal:events')

            event = Event(
                title = title,
                description = description,
                location = location,
                address = address,
                by = by,
                start_date = start_date_time,
                end_date = end_date_time
            )
            
            event.save()
            if(picture != None):
                event.picture = picture
                event.save()

        except Exception as err:
            messages.add_message(request, messages.ERROR, err)
            return redirect('adminportal:events')

    return render(request, 'adminportal/events.html')


@login_required
@user_passes_test(
    is_superuser, redirect_field_name=None,
    login_url=reverse_lazy('home')
)
def registrations_index(request):
    if request.method == 'POST':
        try:
            profile = Profile.objects.get(roll_no=request.POST.get('id'))
            if profile.verify is not None:
                raise RuntimeError("Invalid verification request for roll no. {}.".format(profile.roll_no))

            if 'approve' in request.POST:
                profile.verify = True
                # mail_sent = send_verification_email(get_current_site(request).domain, request.is_secure(), profile)
                # profile.mail_sent = mail_sent
                profile.save()

                # To check if mail_sent was also updated
                profile.refresh_from_db()
                if profile.mail_sent:
                    messages.add_message(request, messages.SUCCESS, "Registration Success, Mail sent to {}".format(profile.name))
                else:
                    messages.add_message(request, messages.ERROR, "Something went wrong. Verification mail not sent to {}".format(profile.name))

            elif 'decline' in request.POST:
                profile.verify = False
                profile.save()
                messages.add_message(request, messages.SUCCESS, "Registration Declined for {}".format(profile.name))

        except Exception as err:
            print(err)
            messages.add_message(request, messages.ERROR, err)

        return redirect('adminportal:registrations')

    unregistered = Profile.objects.filter(verify=None).filter(mail_sent=False).order_by('-user__date_joined')

    context = {
        'pending': unregistered
    }
    return render(request, 'adminportal/registrations.html', context)


@login_required
@user_passes_test(
    is_superuser, redirect_field_name=None,
    login_url=reverse_lazy('home')
)
def mailservice_index(request):
    programmes = Profile.objects.values_list('programme', flat=True).distinct()
    batches = Profile.objects.select_related('batch').values_list('batch__batch', flat=True).distinct()
    branches = Profile.objects.values_list('branch', flat=True).distinct()

    if request.method == 'POST':
        template_id = request.POST['template_id']
        programme = request.POST['programme']
        batch = request.POST['batch']
        branch = request.POST['branch']

        template = EmailTemplate.objects.get(template_id=template_id)
        recipients = Profile.objects.all()

        if programme:
            recipients = recipients.filter(programme=programme)
        if batch:
            recipients = recipients.filter(batch__batch=batch)
        if branch:
            recipients = recipients.filter(branch=branch)

        total_recipients = recipients.count()
        if total_recipients == 0:
            messages.error(request, f"Cannot send email to 0 recipients.")
            return redirect('adminportal:mailservice')

        emails_sent_today = EmailHistory.objects.filter(
            timestamp__date=date.today()
        ).aggregate(Sum('total_delivered'))['total_delivered__sum']

        if emails_sent_today is None:
            emails_sent_today = 0

        total_recipients_allowed = ALLOWED_RECIPIENTS_PER_DAY - emails_sent_today
        if total_recipients > total_recipients_allowed:
            messages.error(request, f"You can only send {total_recipients_allowed} more emails today. Limit: 500 per day.")
            return redirect('adminportal:mailservice')

        email_messages = get_rendered_emails(settings.DEFAULT_FROM_EMAIL, template, recipients)

        try:
            connection = mail.get_connection()
            total_messages_delivered = connection.send_messages(email_messages)
            EmailHistory.objects.create(
                email_template=template.name,
                programme=programme if programme else ', '.join(programmes),
                batch=batch if batch else ', '.join(map(str, batches)),
                branch=branch if branch else ', '.join(branches),
                total_recipients=total_recipients,
                total_delivered=total_messages_delivered,
            )
        except Exception as error:
            print(error)
            messages.error(request, "Something went wrong while sending the emails.")
            return redirect('adminportal:mailservice')

        messages.success(request, f"Email sent successfully to {total_messages_delivered} recipients.")
        return redirect('adminportal:mailservice')

    email_templates = EmailTemplate.objects.all()
    email_history = EmailHistory.objects.all().order_by('-timestamp')

    context = {
        'email_templates': email_templates,
        'email_history': email_history,
        'programmes': programmes,
        'batches': batches,
        'branches': branches,
    }

    return render(request, 'adminportal/mailservice.html', context)

templates/adminportal/admin_navbar.html
<section id="admin_navbar" class="bg-primary p-2">
    <div class="container my-auto">
        <div class="row">
            <div class="col-12 mx-auto align-middle text-center">
                <a href="{% url 'adminportal:index' %}" class="btn btn-light" tabindex="-1" role="button" aria-disabled="true" id="dashboardLnk">Dashboard</a>
                <a href="{% url 'adminportal:mailservice' %}" class="btn btn-light" tabindex="-1" role="button" aria-disabled="true" id="mailingServiceLnk">Mailing Service</a>
                <a href="{% url 'adminportal:registrations' %}" class="btn btn-light" tabindex="-1" role="button" aria-disabled="true" id="registrationsLnk">Registrations</a>
                <a href="/admin/" class="btn btn-light" tabindex="-1" role="button" aria-disabled="true">Database</a>
                <a href="{% url 'adminportal:events' %}" class="btn btn-light" tabindex="-1" role="button" aria-disabled="true" id="eventsLnk">Create an Event</a>
            </div>
        </div>
    </div>
</section>

<script>
    var pathname = window.location.pathname;

    var dashboard = document.getElementById('dashboardLnk');
    var mailingService = document.getElementById('mailingServiceLnk');
    var registrations = document.getElementById('registrationsLnk');
    var events = document.getElementById('eventsLnk');

    if(pathname == '/adminportal/') {
        dashboard.classList.replace('btn-light', 'btn-outline-light');
        dashboard.classList.add('disabled');
    } else if(pathname == '/adminportal/mailservice') {
        mailingService.classList.replace('btn-light', 'btn-outline-light');
        mailingService.classList.add('disabled');
    } else if(pathname == '/adminportal/registrations') {
        registrations.classList.replace('btn-light', 'btn-outline-light');
        registrations.classList.add('disabled');
    } else if(pathname == '/adminportal/events') {
        events.classList.replace('btn-light', 'btn-outline-light');
        events.classList.add('disabled');
    }
</script>

templates/adminportal/events.html
{% extends 'globals/base.html' %}
{% load static %}

{% block title %}
    Events | ArtRoot
{% endblock %}

{% block body %}
    {% include 'globals/navbar.html' %}
    {% include 'adminportal/masthead.html' %}
    {% include 'adminportal/admin_navbar.html' %}
    
    <!-- <section id="services" class="bg-primary p-1">
        <div class="container my-auto">
            <div class="row">
                <div class="col-12 mx-auto align-middle text-center">
                    <a href="{% url 'adminportal:index' %}" class="btn btn-light" tabindex="-1" role="button" aria-disabled="true">Dashboard</a>
                    <a href="{% url 'adminportal:mailservice' %}" class="btn btn-light" tabindex="-1" role="button" aria-disabled="true">Mailing Service</a>
                    <a href="{% url 'adminportal:registrations' %}" class="btn btn-light" tabindex="-1" role="button" aria-disabled="true">Registrations</a>
                    <a href="/admin/" class="btn btn-light" tabindex="-1" role="button" aria-disabled="true">Database</a>
                    <a href="{% url 'adminportal:events' %}" class="btn btn-outline-light disabled" tabindex="-1" role="button" aria-disabled="true">Create an Event</a>
                </div>
            </div>
        </div>
    </section> -->
    
    <div class="container px-5 px-sm-2 my-5">
        <div class="row">
            <div class="col-12">

                {% if messages %}
                    {% for message in messages %}
                        {% if message.tags == 'error' %}
                            <div class="alert alert-danger" role="alert">{{ message }}</div>
                        {% else %}
                            <div class="alert alert-success" role="alert">{{ message }}</div>
                        {% endif %}
                    {% endfor %}
                {% endif %}

                <form method="post" class="mt-4" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="justify-content-center">
                        <div class="form-outline mb-3">
                            <label for="title" class="mx-1">Title:</label>
                            <input type="text" name="title" id="title" class="form-control" required>
                        </div>

                        <div class="form-outline mb-3">
                            <label for="description" class="mx-1">Description:</label>
                            <textarea name="description" id="description" rows="10" class="form-control" required></textarea>
                        </div>

                        <div class="row justify-content-center mb-3">
                            <div class="col-md-6">
                                <div>
                                    <label for="start_date_time" class="mx-1">Start Date:</label>
                                    <input type="datetime-local" name="start_date_time" id="start_date_time" onchange="datetimeValidator()" required>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div>
                                    <label for="end_date_time" class="mx-1">End Date:</label>
                                    <input type="datetime-local" name="end_date_time" id="end_date_time" onchange="datetimeValidator()" required>
                                </div>
                            </div>
                        </div>

                        <div class="form-outline mb-3">
                            <label for="address" class="mx-1">Address:</label>
                            <input type="text" name="address" id="address" class="form-control" required>
                        </div>
                        
                        <div class="form-outline mb-3">
                            <label for="location" class="mx-1">Location (Optional):</label>
                            <input type="text" name="location" id="location" class="form-control">
                        </div>

                        <div class="form-outline mb-3">
                            <label for="organiser" class="mx-1">Organiser (Optional):</label>
                            <input type="text" name="organiser" id="organiser" class="form-control">
                        </div>

                        <div class="form-outline mb-3">
                            <label for="cover_image" class="mx-1">Cover Image (Optional):</label>
                            <input name="cover_image" type="file" id="cover_image" class="form-control-file" accept=".jpg, .jpeg, .png">
                        </div>

                        <div class="row justify-content-center mt-3">
                            <button type="submit" class="col-6 col-sm-4 col-lg-3 btn btn-primary">Submit</button>
                        </div>
                    </div>                
                </form>

            </div>
        </div>
    </div>


    {% include 'globals/footer.html' %}
{% endblock %}


{% block javascript %}
<script type="text/javascript">
    function datetimeValidator() {
        var start_date_time = document.getElementById('start_date_time').value;
        var end_date_time = document.getElementById('end_date_time').value;
        if(start_date_time && end_date_time) {
            if(start_date_time >= end_date_time) {
                alert("Start date & time should be less than end date & time");
            }
        }
    }
</script>
{% endblock %}

templates/adminportal/index.html
{% extends 'globals/base.html' %}
{% load static %}

{% block title %}
    Dashboard | ArtRoot
{% endblock %}

{% block body %}
    {% include 'globals/navbar.html' %}
    {% include 'adminportal/masthead.html' %}
    {% include 'adminportal/admin_navbar.html' %}
      
    <!-- <section id="services" class="bg-primary p-1">
        <div class="container my-auto">
            <div class="row">
                <div class="col-12 mx-auto align-middle text-center">
                    <a href="{% url 'adminportal:index' %}" class="btn btn-outline-light disabled" tabindex="-1" role="button" aria-disabled="true">Dashboard</a>
                   <a href="#" class="btn btn-light" tabindex="-1" role="button" aria-disabled="true">Alumni Card</a>
                   <a href="#" class="btn btn-light" tabindex="-1" role="button" aria-disabled="true">Mail Templates</a>
                    <a href="{% url 'adminportal:mailservice' %}" class="btn btn-light" tabindex="-1" role="button" aria-disabled="true">Mailing Service</a>
                    <a href="{% url 'adminportal:registrations' %}" class="btn btn-light" tabindex="-1" role="button" aria-disabled="true">Registrations</a>
                   <a href="#" class="btn btn-light" tabindex="-1" role="button" aria-disabled="true">Error Logs</a>
                    <a href="/admin/" class="btn btn-light" tabindex="-1" role="button" aria-disabled="true">Database</a>
                    <a href="{% url 'adminportal:events' %}" class="btn btn-light" tabindex="-1" role="button" aria-disabled="true">Create an Event</a>
                </div>
            </div>
        </div>
    </section> -->
    
    <div class="container px-5 px-sm-2 my-5">
        Dashboard page to be updated... :)
    </div>

    {% include 'globals/footer.html' %}
{% endblock %}

templates/adminportal/mailservice.html
{% extends 'globals/base.html' %}
{% load static %}

{% block title %}
    Mail Service
{% endblock %}

{% block body %}
    {% include 'globals/navbar.html' %}
    {% include 'adminportal/masthead.html' %}
    {% include 'adminportal/admin_navbar.html' %}
      
    <!-- <section id="services" class="bg-primary p-1">
        <div class="container my-auto">
            <div class="row">
                <div class="col-12 mx-auto align-middle text-center">
                    <a href="{% url 'adminportal:index' %}" class="btn btn-light" tabindex="-1" role="button" aria-disabled="true">Dashboard</a>
                    <a href="{% url 'adminportal:mailservice' %}" class="btn btn-outline-light disabled" tabindex="-1" role="button" aria-disabled="true">Mailing Service</a>
                    <a href="{% url 'adminportal:registrations' %}" class="btn btn-light" tabindex="-1" role="button" aria-disabled="true">Registrations</a>
                    <a href="/admin/" class="btn btn-light" tabindex="-1" role="button" aria-disabled="true">Database</a>
                    <a href="{% url 'adminportal:events' %}" class="btn btn-light" tabindex="-1" role="button" aria-disabled="true">Create an Event</a>
                </div>
            </div>
        </div>
    </section> -->
    
    <div class="container px-5 px-sm-2 my-5">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'error' %}
                    <div class="alert alert-danger" role="alert">{{ message }}</div>
                {% else %}
                    <div class="alert alert-success" role="alert">{{ message }}</div>
                {% endif %}
            {% endfor %}
        {% endif %}

        <form method="post" class="mt-4" onsubmit="return confirm('Are you sure want to send the email?');">
            {% csrf_token %}
            <div class="row justify-content-center">
                <div class="col-sm-6 col-lg-3 mb-3">
                    <label for="template">Template</label>
                    <select name="template_id" class="form-control" id="template" required>
                        {% for template in email_templates %}
                        <option value="{{ template.template_id }}">{{ template.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-sm-6 col-lg-3 mb-3">
                    <label for="programme">Programme</label>
                    <select name="programme" class="form-control" id="programme">
                        <option value="">All</option>
                        {% for programme in programmes %}
                        <option value="{{ programme }}">{{ programme }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-sm-6 col-lg-3 mb-3">
                    <label for="batch">Batch</label>
                    <select name="batch" class="form-control" id="batch">
                        <option value="">All</option>
                        {% for batch in batches %}
                        <option value="{{ batch }}">{{ batch }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-sm-6 col-lg-3 mb-3">
                    <label for="branch">Branch</label>
                    <select name="branch" class="form-control" id="branch">
                        <option value="">All</option>
                        {% for branch in branches %}
                        <option value="{{ branch }}">{{ branch }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="row justify-content-center mt-3">
                <button type="submit" class="col-6 col-sm-4 col-lg-3 btn btn-primary">Send Email</button>
            </div>
            <div class="row justify-content-center text-center my-3 mx-sm-4">
                Note: Sending email to a lot of people might take some time. Please have patience.
            </div>
        </form>

        <div class="row justify-content-center mt-5">
            <h2 class="text-center mb-4">Email History</h2>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Date & Time</th>
                            <th>Template</th>
                            <th>Programme</th>
                            <th>Batch</th>
                            <th>Branch</th>
                            <th>Recipients</th>
                            <th>Delivered</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for hist in email_history %}
                        <tr>
                            <td>{{ hist.timestamp }}</td>
                            <td>{{ hist.email_template }}</td>
                            <td>{{ hist.programme }}</td>
                            <td>{{ hist.batch }}</td>
                            <td>{{ hist.branch }}</td>
                            <td>{{ hist.total_recipients }}</td>
                            <td>{{ hist.total_delivered }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    {% include 'globals/footer.html' %}
{% endblock %}

templates/adminportal/masthead.html
<div class="p-0 m-0 masthead-bg w-100 parallax shadow-sm"
     style="min-height:300px !important; height:300px !important; background-position-y: 300px;"></div>

<header class="masthead text-center text-white d-flex" style="height:0; min-height:300px;">
    <div class="container my-auto" style="margin-bottom:50px !important;">
        <div class="row">
            <div class="col-lg-8 mx-auto align-middle">
                <h1 class="text-uppercase mt-4">
                    <strong>ADMIN PORTAL</strong>
                </h1>
            </div>
        </div>
    </div>
</header>